export const REALTIME_NOTIFICATIONS_DISABLED =
  process.env.NEXT_PUBLIC_REALTIME_NOTIFICATIONS_DISABLED === "true" ||
  process.env.NEXT_PUBLIC_REALTIME_NOTIFICATIONS_ENABLED === "false";

export const REALTIME_NOTIFICATIONS_ENABLED = !REALTIME_NOTIFICATIONS_DISABLED;
