/**
 * Database type definitions matching Supabase schema
 * This file will be auto-generated by Supabase CLI in production
 * For now, we define types manually
 */

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            jobs: {
                Row: {
                    job_id: number;
                    client_address: string;
                    title: string;
                    description_uri: string | null;
                    description_text: string | null;
                    budget_usdc: number;
                    status: number;
                    hired_freelancer: string | null;
                    escrow_address: string | null;
                    created_at: number;
                    updated_at: number;
                    expires_at: number;
                    tags: string[];
                    synced_at: string;
                    blockchain_block: number | null;
                };
                Insert: {
                    job_id: number;
                    client_address: string;
                    title: string;
                    description_uri?: string | null;
                    description_text?: string | null;
                    budget_usdc: number;
                    status: number;
                    hired_freelancer?: string | null;
                    escrow_address?: string | null;
                    created_at: number;
                    updated_at: number;
                    expires_at: number;
                    tags?: string[];
                    synced_at?: string;
                    blockchain_block?: number | null;
                };
                Update: {
                    job_id?: number;
                    client_address?: string;
                    title?: string;
                    description_uri?: string | null;
                    description_text?: string | null;
                    budget_usdc?: number;
                    status?: number;
                    hired_freelancer?: string | null;
                    escrow_address?: string | null;
                    created_at?: number;
                    updated_at?: number;
                    expires_at?: number;
                    tags?: string[];
                    synced_at?: string;
                    blockchain_block?: number | null;
                };
            };
            freelancer_profiles: {
                Row: {
                    wallet_address: string;
                    profile_contract: string;
                    hourly_rate: number | null;
                    bio: string | null;
                    skills: string[];
                    portfolio_uri: string | null;
                    total_earned: number;
                    jobs_completed: number;
                    average_rating: number | null;
                    kyc_verified: boolean;
                    is_active: boolean;
                    synced_at: string;
                    blockchain_block: number | null;
                };
                Insert: {
                    wallet_address: string;
                    profile_contract: string;
                    hourly_rate?: number | null;
                    bio?: string | null;
                    skills?: string[];
                    portfolio_uri?: string | null;
                    total_earned?: number;
                    jobs_completed?: number;
                    average_rating?: number | null;
                    kyc_verified?: boolean;
                    is_active?: boolean;
                    synced_at?: string;
                    blockchain_block?: number | null;
                };
                Update: {
                    wallet_address?: string;
                    profile_contract?: string;
                    hourly_rate?: number | null;
                    bio?: string | null;
                    skills?: string[];
                    portfolio_uri?: string | null;
                    total_earned?: number;
                    jobs_completed?: number;
                    average_rating?: number | null;
                    kyc_verified?: boolean;
                    is_active?: boolean;
                    synced_at?: string;
                    blockchain_block?: number | null;
                };
            };
            proposals: {
                Row: {
                    id: number;
                    job_id: number;
                    freelancer_address: string;
                    proposal_text: string | null;
                    bid_amount: number;
                    delivery_days: number;
                    applied_at: number;
                    status: string;
                    synced_at: string;
                };
                Insert: {
                    id?: number;
                    job_id: number;
                    freelancer_address: string;
                    proposal_text?: string | null;
                    bid_amount: number;
                    delivery_days: number;
                    applied_at: number;
                    status?: string;
                    synced_at?: string;
                };
                Update: {
                    id?: number;
                    job_id?: number;
                    freelancer_address?: string;
                    proposal_text?: string | null;
                    bid_amount?: number;
                    delivery_days?: number;
                    applied_at?: number;
                    status?: string;
                    synced_at?: string;
                };
            };
            escrows: {
                Row: {
                    escrow_address: string;
                    job_id: number;
                    client_address: string;
                    freelancer_address: string;
                    amount: number;
                    delivered: boolean;
                    disputed: boolean;
                    terminal: boolean;
                    cancel_end: number | null;
                    delivery_due: number | null;
                    review_due: number | null;
                    last_delivery_uri: string | null;
                    last_dispute_uri: string | null;
                    synced_at: string;
                    blockchain_block: number | null;
                };
                Insert: {
                    escrow_address: string;
                    job_id: number;
                    client_address: string;
                    freelancer_address: string;
                    amount: number;
                    delivered?: boolean;
                    disputed?: boolean;
                    terminal?: boolean;
                    cancel_end?: number | null;
                    delivery_due?: number | null;
                    review_due?: number | null;
                    last_delivery_uri?: string | null;
                    last_dispute_uri?: string | null;
                    synced_at?: string;
                    blockchain_block?: number | null;
                };
                Update: {
                    escrow_address?: string;
                    job_id?: number;
                    client_address?: string;
                    freelancer_address?: string;
                    amount?: number;
                    delivered?: boolean;
                    disputed?: boolean;
                    terminal?: boolean;
                    cancel_end?: number | null;
                    delivery_due?: number | null;
                    review_due?: number | null;
                    last_delivery_uri?: string | null;
                    last_dispute_uri?: string | null;
                    synced_at?: string;
                    blockchain_block?: number | null;
                };
            };
            delivery_history: {
                Row: {
                    id: number;
                    escrow_address: string;
                    delivery_uri: string;
                    timestamp: number;
                    version: number;
                    synced_at: string;
                };
                Insert: {
                    id?: number;
                    escrow_address: string;
                    delivery_uri: string;
                    timestamp: number;
                    version: number;
                    synced_at?: string;
                };
                Update: {
                    id?: number;
                    escrow_address?: string;
                    delivery_uri?: string;
                    timestamp?: number;
                    version?: number;
                    synced_at?: string;
                };
            };
            sync_status: {
                Row: {
                    contract_name: string;
                    last_synced_block: number;
                    last_synced_at: string;
                    sync_errors: number;
                    last_error: string | null;
                };
                Insert: {
                    contract_name: string;
                    last_synced_block?: number;
                    last_synced_at?: string;
                    sync_errors?: number;
                    last_error?: string | null;
                };
                Update: {
                    contract_name?: string;
                    last_synced_block?: number;
                    last_synced_at?: string;
                    sync_errors?: number;
                    last_error?: string | null;
                };
            };
        };
        Views: {
            [_ in never]: never;
        };
        Functions: {
            [_ in never]: never;
        };
        Enums: {
            [_ in never]: never;
        };
    };
}
